config/routes.rb
Atos::Application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'visitors#index'
  get '/site-map', to: 'visitors#site_map'
  get '/404', to: 'high_voltage/pages#show', id: '404', as: :page_not_found
  post '/contact', to: 'visitors#send_contact', as: :send_contact
  get '/kontakt', to: 'high_voltage/pages#show', id: 'contact', as: :contact
  get '/index', to: 'visitors#index', as: :index
  get '/blog/:id', to: 'visitors#blog', as: :article
  get '/blog', to: 'visitors#blog', as: :blog
  get '/:id', to: 'visitors#page'
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates_uniqueness_of :url
  validates :url, uniqueness: true, exclusion: {in: %w( admin index users ckeditor 404 pages pictures attachment_files site-map uploader)}
  validates_presence_of :url, :name

  default_scope { order('created_at desc') }

  after_create :expire_cache
  after_save :expire_cache
  after_destroy :expire_cache

  private
  def expire_cache
    ActionController::Base.new.expire_fragment 'articles'
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_presence :data

  def url_content
    url(:content)
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :page, inverse_of: :images

  has_attached_file :img, styles: { thumb: "100x100", portfolio_thumb: "320x229#", portfolio: "1280x720"}, convert_options: {portfolio_thumb:  "-quality 75 -strip", portfolio:  "-quality 85 -strip"}

  def name
    alt
  end

  def delete_img
    @image_delete ||= "0"
  end

  def delete_img=(value)
    @image_delete = value
  end

  before_validation { self.img.clear if self.delete_img == '1' }
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_ancestry
  has_many :images, dependent: :destroy, inverse_of: :page
  accepts_nested_attributes_for :images, allow_destroy: true
  validates_uniqueness_of :url
  validates :url, uniqueness: true, exclusion: {in: %w( admin index users ckeditor 404 pages pictures attachment_files site-map uploader)}
  validates_presence_of :url, :name

  after_create :expire_cache
  after_save :expire_cache
  after_destroy :expire_cache

  private
  def expire_cache
    ActionController::Base.new.expire_fragment 'menu'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def page
    if %w(index Index uvod Uvod home Home).include?(params[:id])
      redirect_to action: :index
    else
      @page = Page.find_by_url(params['id'])
      if @page.nil?
        redirect_to(page_not_found_path)
      else
        path = @page.path.map{|p| "<a href='/#{p.url}'>#{p.menu_name}</a>"}
        @path = path.length > 1 ? path.join(' / ') : ''
        @title = @page.title ? @page.title : @page.name
      end
    end
  end

  def blog
    @article = Article.where(url: params['id']).first
    if @article.nil?
      @articles = Article.all
      @title = "Blog"
    else
      @title = @article.title ? @article.title : @article.name
    end
  end

  def index
    @slide_show = true
  end

  def site_map

  end

  def send_contact
    if verify_recaptcha
      ContactMailer.contact_mail(params["contactm"],params["email"]).deliver
      @message = "<div class='notifications success'><p><strong>Vaša správa bola odoslaná.</strong> Ďakujeme a prajeme pekný deň</p><span class='closer'><i class='icon-cancel-1'></i></span></div>"
    else
      @message = "<div class='notifications error'><p><strong>Nesprávne vyplnený formulár.</strong> Prosím skontrolujte  správnosť údajov (e-mail, správa, overovací kód)</p><span class='closer'><i class='icon-cancel-1'></i></span></div>"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def url_gen(url)
    "#{request.protocol}#{request.host_with_port}#{url}"
  end
end

app/views/layouts/_footer.html.erb
<div class="fullblock">
  <div class="footer padding50">
    <div class="container">
      <div class="row">
        <div class="span4">
          <h1 class="widget-title">O spoločnosti</h1>
          <div class="from-blog-2">
            <p>Spoločnosť A.T.O.S. LR, s.r.o.  sa od svojho založenia v roku 2003 zaoberá výrobou poštových/novinových schránok, rozvádzačov NN, elektroinštalačnými prácami, revíziami výhradných elektrických zariadení a bleskozvodov, výrobou <a href="http://atos.sk/hlinikove-fasady" title="Hliníkové fasády" alt="Hliníkové fasády a hliníkové presklenia">hliníkových konštrukcií</a>, dverí a okien. V poslednom období pri výmene <a href="http://atos.sk/hlinikove-okna-a-dvere" title="Hliníkové okná a dvere" alt="hliníkové okná a dvere">vchodových hliníkových</a> dverí prípadne iných stavebných úpravách v bytových domoch je stále rozšírenejšie komplexné <a href="http://atos.sk/pristupove-systemy" title="Prístupové systémy" alt="prístupové systémy">riešenie vstupov</a> a ich zabezpečenie proti vstupu cudzích ľudí do objektu.</p>
            <p>Súčasťou týchto úprav je aj výber kvalitných hliníkových AL dverí, <a href="http://atos.sk/postove-schranky" title="Poštové schránky" alt="poštové schránky">bezpečných poštových schránok</a> a prístupových systémov.Našou víziou je ponúknuť možnosť všetkým zákazníkom nájsť vždy reálne riešenie svojich predstáv individuálne a cenovo výhodné.</p>
          </div>
        </div>
        <div class="span2">
          <h1 class="widget-title">Kontakt</h1>
          <div class="contact-widget">
            <i class="icon-address"></i>
            <p>
              A.T.O.S. LR, s.r.o.<br />
              Lúčna 8<br />
              971 01 Prievidza
            </p>
            <div class="clearfix"></div>
          </div>
          <h1 class="widget-title">Prevádzka</h1>
          <div class="contact-widget">
            <i class="icon-basket-2"></i>
            <p>
              A. Stodolu 4<br />
              Prievidza 971 01
            </p>
          </div>
        </div>
        <div class="span2">
          <h1 class="widget-title">Telefón</h1>
          <div class="contact-widget">
            <i class="icon-phone"></i>
            <p>
              00421 46 5423627<br />
              00421 915 224 830<br />
              00421 905 280 061
            </p>
            <div class="clearfix"></div>
          </div>
          <h1 class="widget-title">E-mail</h1>
          <div class="contact-widget">
              <i class="icon-mail-3"></i>
              <p>
                E-mail: atos@atos.sk<br>
                Web: <a href="http://www.atos.sk">www.atos.sk</a>
              </p>
            </div>
          </div>
        <div class="span4">
          <iframe style="width:100%;height:200px;" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.sk/maps?t=m&amp;q=48%C2%B046'7.99%22N18%C2%B036'20.34%22E&amp;ie=UTF8&amp;z=11&amp;ll=48.768811,18.605629&amp;output=embed"></iframe>
        </div>
        </div>
      </div>
    </div>
  <div class="copyright">
    <div class="container">
      <p>Copyright 2013   <a href="#">A.T.O.S. LR, s.r.o.</a> Všetky práva vyhradené.</p>
    </div>
  </div>
</div>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-43557671-1', 'atos.sk');
    ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<div class="fullblock">
    <div class="topbar">
      <div class="container">

        <!-- Logo -->
        <div class="logo">
          <%= link_to image_tag('atos.png', alt: 'Atos', height: '44'), root_url %></div>
        <!-- /Logo -->

        <!-- Nav -->
        <nav id="nav">

          <!-- Search -->
          <!--<div class="search-include">-->
            <!--<div class="search-button">-->
              <!--<a href="#"><i class="icon-search"></i></a>-->
            <!--</div>-->
            <!--<div class="popup-search">-->
              <!--<form action="" method="post">-->
                <!--<input type="text" value="Search." onblur="if(this.value=='') this.value='Search.';" onfocus="if(this.value=='Search.') this.value='';" class="ft"/>-->
                <!--<input type="submit" value="" class="fs">-->
              <!--</form>-->
            <!--</div>-->
          <!--</div>-->
          <!-- /Search -->

          <!-- Main Menu -->
          <ul class="sf-menu">
            <%= render 'layouts/navigation' %>
          </ul>
          <!-- /Main Menu -->

          <!-- Mobile Nav Toggler -->
          <div class="nav-toggle">
            <a href="#"></a>
          </div>
        </nav>
        <!-- /Nav -->
      </div>
    </div>

    <!-- Mobile Menu -->
    <div class="mobile-menu">
      <div class="mobile-menu-inner">
        <ul>
            <%= render 'layouts/navigation' %>
        </ul>
      </div>
    </div>
    <!-- /Mobile Menu -->
    <% if @slide_show %>
        <%= render 'layouts/slide_show' %>
    <% end %>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
   <div class="row">
     <div class="span12">
        <div class="notifications <%= name == :notice ? "success" : "error" %>">
          <p>
            <%= msg.html_safe %>
          </p>
          <span class="closer"><i class="icon-cancel-1"></i></span>
        </div>
    </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<% cache('menu', skip_digest: true ) do %>
    <%- Page.roots.all(order: :weight).each do |page| %>
        <li>
          <%= link_to page.menu_name, "/#{page.url}" %>
          <% if page.has_children? %>
            <ul>
                <% page.children.all(order: :weight).each do |child| %>
                  <li>
                    <%= link_to child.menu_name, url_gen("/#{child.url}") %>
                        <% if child.has_children? %>
                            <ul>
                              <% child.children.all(order: :weight).each do |second_child| %>
                                  <li><%= link_to second_child.menu_name, url_gen("/#{second_child.url}") -%></li>
                              <% end %>
                            </ul>
                        <% end %>
                  </li>
                <% end %>
            </ul>
          <% end %>
        </li>
    <% end %>
        <li>
          <%= link_to 'Kontakt', contact_url %>
        </li>
<% end %>

app/views/layouts/_slide_show.html.erb
<!-- Header Slider -->
<div class="head-slider hidden-phone">
  <div class="fullwidthbanner-container">
    <div class="fullwidthbanner">
      <ul>

        <li data-transition="turnoff" data-slotamount="1" data-masterspeed="300">
          <%= image_tag 'slides/DSC00687.jpg' %>
          <div class="caption lfb ltb"
               data-x="80"
               data-y="20"
               data-speed="600"
               data-start="800"
               data-easing="easeOutExpo"  data-endspeed="600" data-endeasing="easeInSine" ><%= image_tag 'slides/schranky-strieborne.png', alt: 'Poštové schránky' %></div>
          <div class="caption randomrotate"
               data-x="280"
               data-y="250"
               data-speed="600"
               data-start="900"
               data-easing="easeOutExpo"  data-endspeed="600" data-endeasing="easeInSine" ><%= image_tag 'slides/LVA_3596.jpg', alt: 'Poštové schránky' %></div>
          <div class="caption mypassion-title-caption-large lfr ltr"
               data-x="550"
               data-y="110"
               data-speed="600"
               data-start="1100"
               data-easing="easeOutExpo"  data-endspeed="600" data-endeasing="easeInSine" >Poštové schránky</div>
          <div class="caption mypassion-greycolor-fixedwidth lfb ltt"
               data-x="620"
               data-y="200"
               data-speed="600"
               data-start="1400"
               data-easing="easeOutExpo" data-endspeed="600" data-endeasing="easeInSine" ><i class="icon-right-open"></i> do hliníkových/plastových dverí </div>
          <div class="caption mypassion-greycolor-fixedwidth lfb ltt"
               data-x="620"
               data-y="245"
               data-speed="600"
               data-start="1600"
               data-easing="easeOutExpo" data-endspeed="600" data-endeasing="easeInSine" ><i class="icon-right-open"></i> do interiérov/exteriérov na stenu </div>
          <div class="caption mypassion-greycolor-fixedwidth lfb ltt"
               data-x="620"
               data-y="290"
               data-speed="600"
               data-start="1800"
               data-easing="easeOutExpo" data-endspeed="600" data-endeasing="easeInSine" ><i class="icon-right-open"></i> do stavebných otvorov </div>
          <div class="caption lfb ltb"
               data-x="750"
               data-y="335"
               data-speed="600"
               data-start="2000"
               data-easing="easeOutExpo"  data-endspeed="600" data-endeasing="easeInSine" ><a href='<%= url_gen "/postove-schranky" %>' class="btn-theme btn-theme-large"><i class="icon-info-circled left"></i> Podrobnosti </a></div>

        </li>

        <!-- THE FIRST SLIDE -->
        <li data-transition="papercut" data-slotamount="10" data-masterspeed="300" >
          <div class="caption lfb ltb"
               data-x="10"
               data-y="70"
               data-speed="600"
               data-start="800"
               data-easing="easeOutExpo"  data-endspeed="600" data-endeasing="easeInSine" ><%= image_tag 'slides/MB45_drzwi.jpg', alt: "Schranky" %></div>

          <div class="caption mypassion-title lft ltt"
               data-x="400"
               data-y="100"
               data-speed="600"
               data-start="900"
               data-easing="easeOutExpo"  data-endspeed="600" data-endeasing="easeInSine" >
            <span style="color:#9a1e21;">Hliníkové dvere a okná</span><br /> podľa požiadaviek zákazníkov
          </div>

          <div class="caption mypassion-text lfr ltr"
               data-x="420"
               data-y="220"
               data-speed="600"
               data-start="1000"
               data-easing="easeOutExpo"  data-endspeed="600" data-endeasing="easeInSine" > <p>Systémy MB pre hliníkové okná a hliníkové dvere sú ponúkané<br /> v rôznych variantách v závislosti od použitia a od požiadavok<br /> týkajucich sa funkčnosti, estetiky, tepelnej izolácie<br /> a protipožiarnej odolnosti.</p></div>

          <div class="caption lfb ltb"
               data-x="500"
               data-y="320"
               data-speed="600"
               data-start="1100"
               data-easing="easeOutExpo"  data-endspeed="600" data-endeasing="easeInSine" ><a href='<%= url_gen("/hlinikove-okna-a-dvere") %>' class="btn-theme btn-theme-large"><i class="icon-info-circled left"></i> Podrobnosti </a></div>
        </li>

        <!-- THE SECOND SLIDE -->
        <li data-transition="3dcurtain-vertical" data-slotamount="15" data-masterspeed="300" data-delay="9400" data-thumb="">
          <%= image_tag 'slides/LVA_3542.jpg' %>

          <div class="caption mypassion-title-caption-large lft ltt"
               data-x="120"
               data-y="50"
               data-speed="600"
               data-start="900"
               data-easing="easeOutExpo" data-endspeed="600" data-endeasing="easeInSine" >Prístupové systémy</div>

          <div class="caption mypassion-greycolor-fixedwidth lfb ltt"
               data-x="120"
               data-y="150"
               data-speed="600"
               data-start="1400"
               data-easing="easeOutExpo" data-endspeed="600" data-endeasing="easeInSine" ><i class="icon-right-open"></i> Digitálne prístupové systémy </div>

          <div class="caption mypassion-greycolor-fixedwidth lfb ltt"
               data-x="120"
               data-y="195"
               data-speed="600"
               data-start="1600"
               data-easing="easeOutExpo"  data-endspeed="600" data-endeasing="easeInSine" ><i class="icon-right-open"></i> Audiotelefóny, videotelefóny, ... </div>

          <div class="caption mypassion-greycolor-fixedwidth lfb ltt"
               data-x="120"
               data-y="240"
               data-speed="600"
               data-start="1800"
               data-easing="easeOutExpo"  data-endspeed="600" data-endeasing="easeInSine" ><i class="icon-right-open"></i> Návrh technického riešenia </div>

          <div class="caption mypassion-greycolor-fixedwidth lfb ltt"
               data-x="120"
               data-y="285"
               data-speed="600"
               data-start="2000"
               data-easing="easeOutExpo"  data-endspeed="600" data-endeasing="easeInSine" ><i class="icon-right-open"></i> Montáž prístupových zariadení </div>

          <div class="caption mypassion-greycolor-fixedwidth lfb ltt"
               data-x="120"
               data-y="330"
               data-speed="600"
               data-start="2200"
               data-easing="easeOutExpo"  data-endspeed="600" data-endeasing="easeInSine" ><i class="icon-right-open"></i> Kompletný záručný a pozáručný servis </div>
          <div class="caption mypassion-greycolor-fixedwidth lfb ltt"
               data-x="120"
               data-y="375"
               data-speed="600"
               data-start="2400"
               data-easing="easeOutExpo"  data-endspeed="600" data-endeasing="easeInSine" ><i class="icon-right-open"></i> Poradenstvo </div>
          <div class="caption lfb ltb"
               data-x="215"
               data-y="425"
               data-speed="600"
               data-start="2600"
               data-easing="easeOutExpo"  data-endspeed="600" data-endeasing="easeInSine" ><a href='<%= url_gen "/pristupove-systemy" %>' class="btn-theme btn-theme-large"><i class="icon-info-circled left"></i> Podrobnosti </a></div>
        </li>

        <li data-transition="papercut" data-slotamount="10" data-masterspeed="300" >
          <%= image_tag 'slides/DSC00512-2.JPG' %>

          <div class="caption mypassion-title-caption-large lfr ltr"
               data-x="600"
               data-y="20"
               data-speed="600"
               data-start="900"
               data-easing="easeOutExpo"  data-endspeed="600" data-endeasing="easeInSine" > Hliníkové fasády</div>
          <div class="caption mypassion-greycolor-fixedwidth lfb ltt"
               data-x="630"
               data-y="80"
               data-speed="600"
               data-start="1100"
               data-easing="easeOutExpo" data-endspeed="600" data-endeasing="easeInSine" > výroba, projekcia, montáž </div>

          <div class="caption lfb ltb"
               data-x="670"
               data-y="124"
               data-speed="600"
               data-start="1400"
               data-easing="easeOutExpo"  data-endspeed="600" data-endeasing="easeInSine" ><a href='<%= url_gen "/hlinikove-fasady" %>' class="btn-theme btn-theme-large"><i class="icon-info-circled left"></i> Podrobnosti </a></div>
        </li>

        <!-- THE THIRD SLIDE -->

      </ul>
      <div class="tp-bannertimer tp-bottom"></div>
    </div>
  </div>
</div>
<!-- /Header Slider -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!--<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">-->
    <meta name="ROBOTS" content="INDEX, FOLLOW">
    <meta name="keywords" content="<%= content_for?(:keywords) ? "#{yield(:keywords)}".html_safe : 'Atos LR – Prístupové systémy | Hliníkové dvere a okná' %>">
    <meta name="description" content="<%= content_for?(:description) ? "#{yield(:description)}".html_safe : 'Atos LR – Prístupové systémy | Hliníkové dvere a okná' %>">
    <link rel="icon" type="image/png" href="/favicon.png"><!-- Major Browsers -->
    <!--[if IE]><link rel="SHORTCUT ICON" href="/favicon.png"/><![endif]--><!-- Internet Explorer-->
    <title><%= content_for?(:title) ? "#{yield(:title)} - Atos LR" : 'Atos LR – Prístupové systémy | Hliníkové dvere a okná' %></title>
    <%= stylesheet_link_tag "application", media: 'all' %>

    <%= csrf_meta_tags %>
    <script type="text/javascript">
        var analytics=analytics||[];(function(){var e=["identify","track","trackLink","trackForm","trackClick","trackSubmit","page","pageview","ab","alias","ready","group","on","once","off"],t=function(e){return function(){analytics.push([e].concat(Array.prototype.slice.call(arguments,0)))}};for(var n=0;n<e.length;n++)analytics[e[n]]=t(e[n])})(),analytics.load=function(e){var t=document.createElement("script");t.type="text/javascript",t.async=!0,t.src=("https:"===document.location.protocol?"https://":"http://")+"d2dq2ahtl5zl1z.cloudfront.net/analytics.js/v1/"+e+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n)};
        analytics.load("r2npn0c9qt");
    </script>
  </head>
  <body>
      <div class="body-wrapper">
        <header id="header">
            <%= render 'layouts/header' %>
        </header>
        <section id="content">
           <%= render 'layouts/messages' %>
           <%= yield %>
        </section>
        <footer id="footer">
          <%= render 'layouts/footer' -%>
        </footer>
      </div>
    <%= javascript_include_tag 'application' %>
    <%= yield :javascript %>
  </body>
</html>

app/views/visitors/_map_ul.html.erb
<ul>
  <%- pages.each do |page| -%>
      <li>
        <%= link_to page.menu_name, url_gen("/#{page.url}") -%>
        <%= render("visitors/map_ul", pages: page.children.all(order: :weight)) if page.has_children? -%>
      </li>
  <%- end -%>
</ul>

app/views/visitors/_sidebar.html.erb
<div class="sidebar">
  <div class="widget-block">
    <p class="sidebar-header">Služby</p>
    <ul>
      <li><p class="sidebar-item"><%= link_to 'Hliníkové dvere a okná', url_gen('/hlinikove-okna-a-dvere') %></p></li>
      <li><p class="sidebar-item"><%= link_to 'Poštové schránky', url_gen('/postove-schranky') %></p></li>
      <li><p class="sidebar-item"><%= link_to 'Prístupové systémy', url_gen('/pristupove-systemy') %></p></li>
      <li><p class="sidebar-item"><%= link_to 'Komunikačné zariadenia', '/audio-video-komunikacne-zariadenia' %></p></li>
      <li><p class="sidebar-item"><%= link_to 'Elektroinštalácie', url_gen('/elektroinstalacie') %></p></li>
      <li><p class="sidebar-item"><%= link_to 'Hliníkové fasády', url_gen('/hlinikove-fasady') %></p></li>
    </ul>
  </div>
  <div class="widget-block">
    <iframe src="//www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fpages%2FATOS-LR-po%25C5%25A1tov%25C3%25A9-schr%25C3%25A1nky-hlin%25C3%25ADkov%25C3%25A9-dvere-a-okn%25C3%25A1-elektroin%25C5%25A1tal%25C3%25A1cie%2F168776793238576&amp;width=300&amp;height=258&amp;colorscheme=light&amp;show_faces=true&amp;header=false&amp;stream=false&amp;show_border=false&amp;appId=180556405337806" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:300px; height:258px;" allowTransparency="true"></iframe>
  </div>
</div>

app/views/visitors/blog.html.erb
<% if @article %>
    <% content_for :title, @title  %>
    <% content_for :description, @article.description %>
    <% content_for :keywords, @article.keywords %>

    <div class="fullblock blockgrey padding20">
      <div class="container">
        <div class="row breadcrumbs">
          <div class="span6">
            <h1><%= @article.name %></h1>
          </div>
          <div class="span6">
            <p>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="fullblock blockwhite padding20" >
      <div class="container">
        <% unless @article.content == '' %>
            <div class="row">
              <div class="span8">
                <div class="blog-post-wrap">
                  <div class="post-desc">
                    <%= @article.content.html_safe -%>
                  </div>
                </div>
              </div>
              <div class="span4 visible-desktop">
                <%= render "sidebar" %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
<% else %>
    <% content_for :title, @title  %>
    <div class="fullblock blockgrey padding20">
      <div class="container">
        <div class="row breadcrumbs">
          <div class="span6">
            <h1><%= @title %></h1>
          </div>
          <div class="span6">
            <p>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="fullblock blockwhite padding20" >
      <div class="container">
            <div class="row">
              <div class="span8">
                    <% @articles.each do |article| %>
                        <div class="blog-post-wrap">
                          <div class="post-type">
                          </div>

                          <div class="post-desc">
                            <h1 class="post-title">
                              <%= link_to article.name, article_path(article.url) %>
                            </h1>
                            <p>
                              <%= Sanitize.clean(article.content)[0..300].html_safe %>...
                              <%= link_to "Viac", article_path(article.url) %>
                            </p>

                          </div>
                        </div>
                    <% end %>
              </div>
              <div class="span4 visible-desktop">
                <%= render "sidebar" %>
              </div>
            </div>
      </div>
    </div>
<% end %>

app/views/visitors/send_contact.js.erb
$('.alertMessage').fadeOut(1).html('<%=j @message.html_safe %>').fadeIn(1500);
$('html, body').animate({
    scrollTop: $(".post-desc").offset().top - 100
}, 2000);